<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreatePermissionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('permissions', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('for');
            $table->integer('stat')->default(0);
            $table->timestamps();
        });

        Schema::create('permission_role', function (Blueprint $table) {
            $table->bigInteger('role_id');
            $table->bigInteger('permission_id');
        });

        DB::table('permissions')->insert([
            [
                'id' => 1,
                'for' => 'Admins',
                'name' => 'admin-view',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 2,
                'for' => 'Admins',
                'name' => 'admin-store',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 3,
                'for' => 'Admins',
                'name' => 'admin-update',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 4,
                'for' => 'Admins',
                'name' => 'admin-delete',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 5,
                'for' => 'Roles',
                'name' => 'role-view',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 6,
                'for' => 'Roles',
                'name' => 'role-store',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 7,
                'for' => 'Roles',
                'name' => 'role-update',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 8,
                'for' => 'Roles',
                'name' => 'role-delete',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 9,
                'for' => 'Roles',
                'name' => 'role-permission',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 10,
                'for' => 'Permissions',
                'name' => 'permission-view',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 11,
                'for' => 'Permissions',
                'name' => 'permission-store',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 12,
                'for' => 'Permissions',
                'name' => 'permission-update',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 13,
                'for' => 'Permissions',
                'name' => 'permission-delete',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 14,
                'for' => 'Branch',
                'name' => 'branch-view',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 15,
                'for' => 'Branch',
                'name' => 'branch-store',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 16,
                'for' => 'Branch',
                'name' => 'branch-update',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 17,
                'for' => 'Branch',
                'name' => 'branch-delete',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 18,
                'for' => 'Customer',
                'name' => 'customer-view',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 19,
                'for' => 'Customer',
                'name' => 'customer-store',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 20,
                'for' => 'Customer',
                'name' => 'customer-update',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 21,
                'for' => 'Customer',
                'name' => 'customer-delete',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 22,
                'for' => 'Customer',
                'name' => 'customer-info',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 23,
                'for' => 'Vendor',
                'name' => 'vendor-view',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 24,
                'for' => 'Vendor',
                'name' => 'vendor-store',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 25,
                'for' => 'Vendor',
                'name' => 'vendor-update',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 26,
                'for' => 'Vendor',
                'name' => 'vendor-delete',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 27,
                'for' => 'Vendor',
                'name' => 'vendor-info',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 28,
                'for' => 'StockMaster',
                'name' => 'stock-master-view',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 29,
                'for' => 'StockMaster',
                'name' => 'stock-master-store',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 30,
                'for' => 'StockMaster',
                'name' => 'stock-master-update',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 31,
                'for' => 'StockMaster',
                'name' => 'stock-master-delete',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 32,
                'for' => 'StockMaster',
                'name' => 'stock-master-movement',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 33,
                'for' => 'Pricelist',
                'name' => 'pricelist-view',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 34,
                'for' => 'Pricelist',
                'name' => 'pricelist-update',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 35,
                'for' => 'SPBD',
                'name' => 'spbd-view',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 36,
                'for' => 'SPBD',
                'name' => 'spbd-store',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 37,
                'for' => 'SPBD',
                'name' => 'spbd-update',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 38,
                'for' => 'SPBD',
                'name' => 'spbd-delete',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 39,
                'for' => 'SPBD',
                'name' => 'spbd-open',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 40,
                'for' => 'SPBD',
                'name' => 'spbd-approve',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 41,
                'for' => 'SPBD',
                'name' => 'spbd-print',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 42,
                'for' => 'PoStock',
                'name' => 'po-stock-view',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 43,
                'for' => 'PoStock',
                'name' => 'po-stock-store',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 44,
                'for' => 'PoStock',
                'name' => 'po-stock-update',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 45,
                'for' => 'PoStock',
                'name' => 'po-stock-delete',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 46,
                'for' => 'PoStock',
                'name' => 'po-stock-open',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 47,
                'for' => 'PoStock',
                'name' => 'po-stock-verify',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 48,
                'for' => 'PoStock',
                'name' => 'po-stock-approve',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 49,
                'for' => 'PoStock',
                'name' => 'po-stock-print',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 50,
                'for' => 'Receipt',
                'name' => 'receipt-view',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 51,
                'for' => 'Receipt',
                'name' => 'receipt-store',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 52,
                'for' => 'Receipt',
                'name' => 'receipt-update',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 53,
                'for' => 'Receipt',
                'name' => 'receipt-delete',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 54,
                'for' => 'Receipt',
                'name' => 'receipt-open',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 55,
                'for' => 'Receipt',
                'name' => 'receipt-print',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 56,
                'for' => 'SPB',
                'name' => 'spb-view',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 57,
                'for' => 'SPB',
                'name' => 'spb-store',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 58,
                'for' => 'SPB',
                'name' => 'spb-update',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 59,
                'for' => 'SPB',
                'name' => 'spb-delete',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 60,
                'for' => 'SPB',
                'name' => 'spb-open',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 61,
                'for' => 'SPB',
                'name' => 'spb-approve',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 62,
                'for' => 'SPB',
                'name' => 'spb-print',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 63,
                'for' => 'PoNonStock',
                'name' => 'po-non-stock-view',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 64,
                'for' => 'PoNonStock',
                'name' => 'po-non-stock-store',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 65,
                'for' => 'PoNonStock',
                'name' => 'po-non-stock-update',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 66,
                'for' => 'PoNonStock',
                'name' => 'po-non-stock-delete',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 67,
                'for' => 'PoNonStock',
                'name' => 'po-non-stock-open',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 68,
                'for' => 'PoNonStock',
                'name' => 'po-non-stock-verify',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 69,
                'for' => 'PoNonStock',
                'name' => 'po-non-stock-approve',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 70,
                'for' => 'PoNonStock',
                'name' => 'po-non-stock-print',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 71,
                'for' => 'SPPB',
                'name' => 'sppb-view',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 72,
                'for' => 'SPPB',
                'name' => 'sppb-store',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 73,
                'for' => 'SPPB',
                'name' => 'sppb-update',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 74,
                'for' => 'SPPB',
                'name' => 'sppb-delete',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 75,
                'for' => 'SPPB',
                'name' => 'sppb-open',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 76,
                'for' => 'SPPB',
                'name' => 'sppb-approve',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 77,
                'for' => 'SPPB',
                'name' => 'sppb-print',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 78,
                'for' => 'PoInternal',
                'name' => 'po-internal-view',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 79,
                'for' => 'PoInternal',
                'name' => 'po-internal-store',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 80,
                'for' => 'PoInternal',
                'name' => 'po-internal-update',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 81,
                'for' => 'PoInternal',
                'name' => 'po-internal-delete',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 82,
                'for' => 'PoInternal',
                'name' => 'po-internal-open',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 83,
                'for' => 'PoInternal',
                'name' => 'po-internal-approve',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 84,
                'for' => 'PoInternal',
                'name' => 'po-internal-print',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 85,
                'for' => 'Invoice',
                'name' => 'invoice-view',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 86,
                'for' => 'Invoice',
                'name' => 'invoice-store',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 87,
                'for' => 'Invoice',
                'name' => 'invoice-update',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 88,
                'for' => 'Invoice',
                'name' => 'invoice-delete',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 89,
                'for' => 'Invoice',
                'name' => 'invoice-open',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 90,
                'for' => 'Invoice',
                'name' => 'invoice-verify',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 91,
                'for' => 'Invoice',
                'name' => 'invoice-approve',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 92,
                'for' => 'Invoice',
                'name' => 'invoice-print',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 93,
                'for' => 'Adjustment',
                'name' => 'adjustment-view',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 94,
                'for' => 'Adjustment',
                'name' => 'adjustment-store',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 95,
                'for' => 'Adjustment',
                'name' => 'adjustment-update',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 96,
                'for' => 'Adjustment',
                'name' => 'adjustment-delete',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 97,
                'for' => 'Adjustment',
                'name' => 'adjustment-open',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 98,
                'for' => 'Adjustment',
                'name' => 'adjustment-old',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 99,
                'for' => 'Adjustment',
                'name' => 'adjustment-approve',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 100,
                'for' => 'Adjustment',
                'name' => 'adjustment-print',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 101,
                'for' => 'Pelunasan',
                'name' => 'pelunasan-view',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 102,
                'for' => 'Pelunasan',
                'name' => 'pelunasan-store',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 103,
                'for' => 'Pelunasan',
                'name' => 'pelunasan-update',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 104,
                'for' => 'Pelunasan',
                'name' => 'pelunasan-delete',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 105,
                'for' => 'Pelunasan',
                'name' => 'pelunasan-approve',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 106,
                'for' => 'Pelunasan',
                'name' => 'pelunasan-print',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 107,
                'for' => 'Pembatalan',
                'name' => 'pembatalan-view',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 108,
                'for' => 'Pembatalan',
                'name' => 'pembatalan-po-stock',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 109,
                'for' => 'Pembatalan',
                'name' => 'pembatalan-po-non_stock',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 110,
                'for' => 'Pembatalan',
                'name' => 'pembatalan-invoice',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
            [
                'id' => 111,
                'for' => 'Admins',
                'name' => 'admin-branch',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'stat' => 1,
            ],
        ]);

        DB::table('permission_role')->insert([
            ['role_id' => 1,'permission_id' => 1],
            ['role_id' => 1,'permission_id' => 2],
            ['role_id' => 1,'permission_id' => 3],
            ['role_id' => 1,'permission_id' => 4],
            ['role_id' => 1,'permission_id' => 5],
            ['role_id' => 1,'permission_id' => 6],
            ['role_id' => 1,'permission_id' => 7],
            ['role_id' => 1,'permission_id' => 8],
            ['role_id' => 1,'permission_id' => 9],
            ['role_id' => 1,'permission_id' => 10],
            ['role_id' => 1,'permission_id' => 11],
            ['role_id' => 1,'permission_id' => 12],
            ['role_id' => 1,'permission_id' => 13],
            ['role_id' => 1,'permission_id' => 14],
            ['role_id' => 1,'permission_id' => 15],
            ['role_id' => 1,'permission_id' => 16],
            ['role_id' => 1,'permission_id' => 17],
            ['role_id' => 1,'permission_id' => 18],
            ['role_id' => 1,'permission_id' => 19],
            ['role_id' => 1,'permission_id' => 20],
            ['role_id' => 1,'permission_id' => 21],
            ['role_id' => 1,'permission_id' => 22],
            ['role_id' => 1,'permission_id' => 23],
            ['role_id' => 1,'permission_id' => 24],
            ['role_id' => 1,'permission_id' => 25],
            ['role_id' => 1,'permission_id' => 26],
            ['role_id' => 1,'permission_id' => 27],
            ['role_id' => 1,'permission_id' => 28],
            ['role_id' => 1,'permission_id' => 29],
            ['role_id' => 1,'permission_id' => 30],
            ['role_id' => 1,'permission_id' => 31],
            ['role_id' => 1,'permission_id' => 32],
            ['role_id' => 1,'permission_id' => 33],
            ['role_id' => 1,'permission_id' => 34],
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('permissions');
    }
}
